# Telescope DNS Configure File

listen = ":53/udp"  # 监听端口，支持指定tcp/udp，不指定时默认同时监听tcp&udp
gfwlist = "config/gfwlist.txt"
gfwlist_b64 = true
cnip = "config/china_ip_list.txt"
disable_qtypes = ["AAAA", "HTTPS"]

hosts_files = ["/etc/hosts"]
[hosts]
"clientlog3.music.163.com" = "music.163.com"
"live-vts.lol.qq.com" = "127.0.0.1"
"qqlive.qq.com" = "127.0.0.1"
"researchnet.qqlive.qq.com" = "127.0.0.1"

[query_log]
file = ""  # dns请求日志文件，值为/dev/null时不记录，值为空时记录到stdout
ignore_qtypes = ["DNSKEY", "NS"]  # 不记录指定类型的dns请求，默认为空
ignore_cache = false  # 不记录命中缓存的dns请求，默认为false
ignore_hosts = true  # 不记录命中hosts的dns请求，默认为false

[cache]  # dns缓存配置
size = 65536  # 缓存大小，为负数时禁用缓存
min_ttl = 3600  # 最小ttl，单位为秒
max_ttl = 86400  # 最大ttl，单位为秒

[groups] # 对域名进行分组
[groups.inside]  # 必选分组，默认域名所在分组
# ecs = "1.2.4.0/24"
no_cookie = true
dns = ["127.0.0.1:5301"]  # DNS服务器列表，默认使用53端口
concurrent = true  # 并发请求dns服务器列表
rules = []  # "qq.com"规则可匹配"test.qq.com"、"qq.com"两种域名，".qq.com"和"*.qq.com"规则无法匹配"qq.com"
rules_file = "config/rules.txt"  # 规则文件，每行一个规则

fastest_v4 = true  # 选择ping值最低的ipv4地址作为响应，启用且使用icmp ping时建议以root权限允许本程序
tcp_ping_port = 80  # 当启用fastest_v4时，如该值大于0则使用tcp ping，小于等于0则使用icmp ping

[groups.outside]  # 必选分组，匹配GFWList的域名会归类到该组
# socks5 = "127.0.0.1:1080"  # 当使用国外53端口dns解析时推荐用socks5代理解析
dns = ["127.0.0.1:5302"]  # 如不想用socks5代理解析时推荐使用国外非53端口dns

# 警告：进程启动时会覆盖已有同名IPSet
#ipset = "blocked"  # 目标IPSet名称，该组所有域名的ipv4解析结果将加入到该IPSet中
#ipset_ttl = 86400 # ipset记录超时时间，单位为秒，推荐设置以避免ipset记录过多

# 可选自定义分组，用于其它情况
# 比如办公网内，内外域名（company.com）用内网dns（10.1.1.1）解析
[groups.work]

[groups.blocked]
dns = ["127.0.0.53"]
rules = ["company.com"]